# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.10-slim

# Install Suricata
RUN apt-get update \
    && apt-get install -y suricata \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY . /app

# Update config.py to use Linux Suricata binary path
RUN sed -i 's#^SURICATA_DIR =.*#SURICATA_DIR = "/usr/bin"#' config.py \
    && sed -i 's#^SURICATA_EXE_FILE =.*#SURICATA_EXE_FILE = "suricata"#' config.py

# Install Python dependencies
RUN pip install --no-cache-dir --ignore-installed -r requirements.txt

# Set environment for Python
ENV PYTHONUNBUFFERED=1

# Default command
CMD ["python", "suricata-mcp.py"]
